version: "3.9"
services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - web
      - server

  web:
    build:
      context: ./frontend/
      dockerfile: Dockerfile

  server:
    build:
      context: ./backend/
      dockerfile: Dockerfile

  postgre:
    image: postgres:latest
    environment:
      POSTGRES_DB: "goals_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
#    volumes:
#      - ./db_backups:/docker-entrypoint-initdb.d
    ports:
        - "5432:5432"
volumes:
  logvolume01: { }