CREATE SEQUENCE IF NOT EXISTS task_sequence START WITH 1 INCREMENT BY 10;

CREATE TABLE country
(
    id       BIGINT NOT NULL,
    name     VARCHAR(255),
    crt_date TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE goal_table
(
    id          BIGINT NOT NULL,
    uid         BIGINT,
    title       VARCHAR(255),
    description VARCHAR(255),
    is_done     BOOLEAN,
    gid         BIGINT,
    root        BIGINT,
    priority    INTEGER,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deadline    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_goal_table PRIMARY KEY (id)
);

CREATE TABLE user_settings_table
(
    uid             BIGINT NOT NULL,
    user_language   VARCHAR(255),
    started_page    VARCHAR(255),
    time_format     VARCHAR(255),
    date_format     VARCHAR(255),
    theme           VARCHAR(255),
    auto_dark_theme BOOLEAN,
    CONSTRAINT pk_user_settings_table PRIMARY KEY (uid)
);

CREATE TABLE user_table
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255),
    name          VARCHAR(255),
    surname       VARCHAR(255),
    male          BOOLEAN,
    email         VARCHAR(255),
    locality      BIGINT,
    password      VARCHAR(255),
    admin         BOOLEAN,
    user_photo_id BIGINT,
    settings_uid  BIGINT,
    CONSTRAINT pk_user_table PRIMARY KEY (id)
);

CREATE TABLE users_avatar
(
    id             BIGINT NOT NULL,
    file_extension VARCHAR(255),
    CONSTRAINT pk_users_avatar PRIMARY KEY (id)
);

ALTER TABLE user_table
    ADD CONSTRAINT FK_USER_TABLE_ON_SETTINGS_UID FOREIGN KEY (settings_uid) REFERENCES user_settings_table (uid);

ALTER TABLE user_table
    ADD CONSTRAINT FK_USER_TABLE_ON_USERPHOTO FOREIGN KEY (user_photo_id) REFERENCES users_avatar (id);